### ISSUE TITLE
fort object does not return name ,image of pokestop and gyms 

### ISSUE THREAD

**Issue by uzaif313** [gallexme/pokemongo-api#10]

**Comment by st0ffern** [comment]
@uzaif313 and it should not do that..

```
fort.details()
checkpoint.details()
```

https://github.com/gallexme/pokemongo-api#fort-object-checkpoint-and-gym

**Comment by uzaif313** [comment]
can you tell me how to get `fort` object i try this way `objects.forts` and iterate in for loop

**Comment by st0ffern** [comment]
Have you looked at the example?
https://github.com/gallexme/pokemongo-api/blob/master/example/example.js

**Comment by uzaif313** [comment]
I resolved it  
Thanks for response @stoffern i really appreciate your help
can you provide method with which i can get `gyms` and `pokestops` from different lat-long

**Comment by st0ffern** [comment]
@uzaif313 not possible. then you need to move there
