### ISSUE TITLE
TypeError: Cannot read property 'push' of null

### ISSUE THREAD

**Issue by uzaif313** [gallexme/pokemongo-api#9]
I got this when i am running test example 
`node example-es5/example.js`

**Comment by st0ffern** [comment]
it is ES6
you should either run it throu babel-node or compile it until nodejs supports ES6

**Comment by uzaif313** [comment]
i compile it with package.json script tag which mention like `npm run compile`

**Comment by st0ffern** [comment]
compile-example

**Comment by uzaif313** [comment]
yes it generated new folder named as `example-es5`

**Comment by marcelaraujo** [comment]
@stoffern 

```
var res = this.signatureBuilder.encrypt(req, (err, sigEncrypted) => {

        console.log(data) //data.unknown6 is null

        data.unknown6.push(new POGOProtos.Networking.Envelopes.Unknown6({
            request_type: 6,
            unknown2: new POGOProtos.Networking.Envelopes.Unknown6.Unknown2({
                encrypted_signature: sigEncrypted
            })
        }))
      })
```

**Comment by st0ffern** [comment]
@marcelaraujo looks like they updated the node-pogo-protos... updated the repo now.. NPM out shortly
https://github.com/gallexme/pokemongo-api/commit/5d3047bcee7281128d04f6a0ba6c661f333ae815
